/// The store that issued a partner's promotional offer code.
///
/// SpotVibe never creates its own Premium-unlock codes. Codes tracked here are
/// created by App Store Connect or Google Play Console, then stocked and issued
/// by an administrator from the app.
enum PartnerPromoPlatform { android, ios }

PartnerPromoPlatform partnerPromoPlatformFromName(String? value) {
  for (final platform in PartnerPromoPlatform.values) {
    if (platform.name == value) return platform;
  }
  return PartnerPromoPlatform.android;
}

/// An issued code cannot be reissued, even if the store redemption has not yet
/// been observed. Storefronts remain the source of truth for redemption.
enum PartnerPromoStatus { available, issued, revoked }

PartnerPromoStatus partnerPromoStatusFromName(String? value) {
  for (final status in PartnerPromoStatus.values) {
    if (status.name == value) return status;
  }
  return PartnerPromoStatus.available;
}

class PartnerPromoCode {
  final String id;

  /// The code generated by App Store Connect or Google Play Console.
  final String code;
  final PartnerPromoPlatform platform;

  /// Human-readable reference to the exact store offer, for example
  /// "Partner Premium — 90-day free period".
  final String offerLabel;
  final String durationLabel;
  final PartnerPromoStatus status;

  final String createdBy;
  final DateTime createdAt;
  final String? partnerName;
  final String? partnerEmail;
  final String? issuedBy;
  final DateTime? issuedAt;
  final String? revokedBy;
  final DateTime? revokedAt;

  const PartnerPromoCode({
    required this.id,
    required this.code,
    required this.platform,
    required this.offerLabel,
    required this.durationLabel,
    required this.status,
    required this.createdBy,
    required this.createdAt,
    this.partnerName,
    this.partnerEmail,
    this.issuedBy,
    this.issuedAt,
    this.revokedBy,
    this.revokedAt,
  });

  bool get isAvailable => status == PartnerPromoStatus.available;
  bool get isIssued => status == PartnerPromoStatus.issued;
  bool get isRevoked => status == PartnerPromoStatus.revoked;

  String get platformLabel => switch (platform) {
        PartnerPromoPlatform.android => 'Google Play',
        PartnerPromoPlatform.ios => 'App Store',
      };

  String get statusLabel => switch (status) {
        PartnerPromoStatus.available => 'Available',
        PartnerPromoStatus.issued => 'Issued',
        PartnerPromoStatus.revoked => 'Revoked',
      };

  PartnerPromoCode copyWith({
    PartnerPromoStatus? status,
    String? partnerName,
    String? partnerEmail,
    String? issuedBy,
    DateTime? issuedAt,
    String? revokedBy,
    DateTime? revokedAt,
  }) =>
      PartnerPromoCode(
        id: id,
        code: code,
        platform: platform,
        offerLabel: offerLabel,
        durationLabel: durationLabel,
        status: status ?? this.status,
        createdBy: createdBy,
        createdAt: createdAt,
        partnerName: partnerName ?? this.partnerName,
        partnerEmail: partnerEmail ?? this.partnerEmail,
        issuedBy: issuedBy ?? this.issuedBy,
        issuedAt: issuedAt ?? this.issuedAt,
        revokedBy: revokedBy ?? this.revokedBy,
        revokedAt: revokedAt ?? this.revokedAt,
      );
}
